// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://virjapicssxbtkopxiep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpcmphcGljc3N4YnRrb3B4aWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjIzMzQsImV4cCI6MjA2NTQ5ODMzNH0.e_aYkkGPsoZmWw7w2ZkkPhXPE91PhuYjoWj-wxpzmQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);